### ISSUE TITLE
Import chrome into zhallnzon build

### ISSUE THREAD

**Issue by KOYK** [OpenOP2/OpenOP2#27]
- [x] Tokamak
- [x] Smelter - Common
- [x] Factory - Vehicle
- [x] Guard post - Laser
- [x] Cargo Truck
- [x] Robo-Miner
- [x] Robo-Dozer
- [ ] Lynx - Laser

**This issue was transferred from https://trello.com/b/7YUmxY82/openop2 as it is, further editing might be required.**

**Comment by shpookys** [comment]
branch no longer exists and chrome for units added to master
