### ISSUE TITLE
Unit and Building Catalog

### ISSUE THREAD

**Issue by KOYK** [OpenOP2/OpenOP2#37]
A document with basic information about each Unit and Building from Outpost 2 including cost, health, and upgrades

@Zhall
Brian Esquivel
10 Jun 2020 22:41
The back of the manual has good insight on this.

But these pages are better.

wiki.outpost2.net/doku.php?id=outpost_2:outpost_2_manual:unit_reference

wiki.outpost2.net/doku.php?id=outpost_2:outpost_2_manual:vehicles

wiki.outpost2.net/doku.php?id=outpost_2:outpost_2_manual:weapons

**This issue was transferred from https://trello.com/b/7YUmxY82/openop2 as it is, further editing might be required.**

**Comment by shpookys** [comment]
game files were extracted that explain all of this
