### ISSUE TITLE
Research Documentation

### ISSUE THREAD

**Issue by KOYK** [OpenOP2/OpenOP2#43]
Augment the existing Outpost 2 Wiki of Research/Tech tree with more detailed information, such as impacts to HP, etc.

@Zhall
Brian Esquivel
10 Jun 2020 22:33
Most of the details for this can be found here

wiki.outpost2.net/doku.php?id=outpost_2:outpost_2_manual:research

**This issue was transferred from https://trello.com/b/7YUmxY82/openop2 as it is, further editing might be required.**

**Comment by shpookys** [comment]
documentation exists and we have access op2's code that describes this information
